apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: kubeadm-2
  namespace: liqo-team
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.90.0.0/16
    services:
      cidrBlocks:
      - 10.95.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: kubeadm-2-control-plane
    namespace: liqo-team
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KubevirtCluster
    name: kubeadm-2
    namespace: liqo-team
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  name: kubeadm-2
  namespace: liqo-team
spec:
  controlPlaneServiceTemplate:
    spec:
      type: ClusterIP
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: kubeadm-2-control-plane
  namespace: liqo-team
spec:
  template:
    spec:
      virtualMachineTemplate:
        metadata:
          namespace: liqo-team
        spec:
          runStrategy: Always
          template:
            spec:
              domain:
                cpu:
                  cores: 2
                devices:
                  disks:
                  - disk:
                      bus: virtio
                    name: containervolume
                  networkInterfaceMultiqueue: true
                memory:
                  guest: 4Gi
              evictionStrategy: External
              volumes:
              - containerDisk:
                  image: harbor.crownlabs.polito.it/capk/ubuntu-2204-container-disk:v1.28.5
                name: containervolume
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: kubeadm-2-control-plane
  namespace: liqo-team
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      networking:
        dnsDomain: kubeadm-2.liqo-team.local
        podSubnet: 10.90.0.0/16
        serviceSubnet: 10.95.0.0/16
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: KubevirtMachineTemplate
      name: kubeadm-2-control-plane
      namespace: liqo-team
  replicas: 1
  version: 1.28.5
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: kubeadm-2-md-0
  namespace: liqo-team
spec:
  template:
    spec:
      virtualMachineTemplate:
        metadata:
          namespace: liqo-team
        spec:
          runStrategy: Always
          template:
            spec:
              domain:
                cpu:
                  cores: 4
                devices:
                  disks:
                  - disk:
                      bus: virtio
                    name: containervolume
                  networkInterfaceMultiqueue: true
                memory:
                  guest: 8Gi
              evictionStrategy: External
              volumes:
              - containerDisk:
                  image: harbor.crownlabs.polito.it/capk/ubuntu-2204-container-disk:v1.28.5
                name: containervolume
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: kubeadm-2-md-0
  namespace: liqo-team
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs: {}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: kubeadm-2-md-0
  namespace: liqo-team
spec:
  clusterName: kubeadm-2
  replicas: 2
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: kubeadm-2-md-0
          namespace: liqo-team
      clusterName: kubeadm-2
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: KubevirtMachineTemplate
        name: kubeadm-2-md-0
        namespace: liqo-team
      version: 1.28.5
